export default {
	COMPLETE_ITEM: 'COMPLETE_ITEM',
	LOAD_CHECKLISTS: 'LOAD_CHECKLISTS',

	GET_POMODORO_ARCHIVE_SUCCESS: 'GET_POMODORO_ARCHIVE_SUCCESS',

	GET_ACTIVE_POMODORO_SUCCESS: 'GET_ACTIVE_POMODORO_SUCCESS',
	INCREMENT_ACTIVE_POMODORO_SUCCESS: 'INCREMENT_ACTIVE_POMODORO_SUCCESS',

	GET_TASKS_SUCCESS: 'GET_TASKS_SUCCESS',

	GET_NOTES_SUCCESS: 'GET_NOTES_SUCCESS',

	BEGIN_API_CALL: 'BEGIN_API_CALL',
	API_CALL_ERROR: 'API_CALL_ERROR',



	GET_WEIGHT_DATA_SUCCESS: 'GET_WEIGHT_DATA_SUCCESS',

	GET_YESTERDAYS_POMODOROS_SUCCESS: 'GET_YESTERDAYS_POMODOROS_SUCCESS',

	// websockets
	LOG_COMPULSION: 'LOG_COMPULSION',

	GET_TODAYS_ACTIVE_MINUTES: 'GET_TODAYS_ACTIVE_MINUTES',
	GET_TODAYS_ACTIVE_MINUTES_SUCCESS: 'GET_TODAYS_ACTIVE_MINUTES_SUCCESS',

	GET_POINT_RULES: 'GET_POINT_RULES',
	GET_POINT_RULES_SUCCESS: 'GET_POINT_RULES_SUCCESS',

	GET_POINTS: 'GET_POINTS',
	GET_TODAYS_HEALTH_BAR: 'GET_TODAYS_HEALTH_BAR',
	GET_TODAYS_HEALTH_BAR_SUCCESS: 'GET_TODAYS_HEALTH_BAR_SUCCESS',

	GET_ENTIRE_ARCHIVE: 'GET_ENTIRE_ARCHIVE',
	GET_ENTIRE_ARCHIVE_SUCCESS: 'GET_ENTIRE_ARCHIVE_SUCCESS',

	GET_CONTINUOUS_GOALS: 'GET_CONTINUOUS_GOALS',
	GET_CONTINUOUS_GOALS_SUCCESS: 'GET_CONTINUOUS_GOALS_SUCCESS',

	LOG_MEAL: 'LOG_MEAL',
	GET_YESTERDAYS_MEALS: 'GET_YESTERDAYS_MEALS',
	GET_YESTERDAYS_MEALS_SUCCESS: 'GET_YESTERDAYS_MEALS_SUCCESS',
	GET_TODAYS_MEALS: 'GET_TODAYS_MEALS',
	GET_TODAYS_MEALS_SUCCESS: 'GET_TODAYS_MEALS_SUCCESS',

	GET_BUDGET_CATEGORIES: 'GET_BUDGET_CATEGORIES',
	GET_BUDGET_ACCOUNTS: 'GET_BUDGET_ACCOUNTS',
	GET_BUDGET_CURRENT_MONTH: 'GET_BUDGET_CURRENT_MONTH',
	GET_BUDGET_MONTH: 'GET_BUDGET_MONTH',
	GET_BUDGET_CATEGORIES_SUCCESS: 'GET_BUDGET_CATEGORIES_SUCCESS',
	GET_BUDGET_ACCOUNTS_SUCCESS: 'GET_BUDGET_ACCOUNTS_SUCCESS',
	GET_BUDGET_CURRENT_MONTH_SUCCESS: 'GET_BUDGET_CURRENT_MONTH_SUCCESS',
	GET_BUDGET_MONTH_SUCCESS: 'GET_BUDGET_MONTH_SUCCESS',

	GET_TODAYS_TASKS: 'GET_TODAYS_TASKS',
	GET_TODAYS_TASKS_SUCCESS: 'GET_TODAYS_TASKS_SUCCESS',

	START_AUTO_REFRESH: 'START_AUTO_REFRESH',
	STOP_AUTO_REFRESH: 'STOP_AUTO_REFRESH',

	GET_MORNING_CHECKLIST: 'GET_MORNING_CHECKLIST',
	GET_MORNING_CHECKLIST_SUCCESS: 'GET_MORNING_CHECKLIST_SUCCESS',
	COMPLETE_MORNING_CHECKLIST_ITEM: 'COMPLETE_MORNING_CHECKLIST_ITEM',

	GET_TODAYS_POMODOROS: 'GET_TODAYS_POMODOROS',
	GET_TODAYS_POMODOROS_SUCCESS: 'GET_TODAYS_POMODOROS_SUCCESS',

	GET_TODAYS_PAST_LOGS: 'GET_TODAYS_PAST_LOGS',
	GET_TODAYS_PAST_LOGS_SUCCESS: 'GET_TODAYS_PAST_LOGS_SUCCESS',

	GET_RANDOM_QUOTE: 'GET_RANDOM_QUOTE',
	GET_RANDOM_QUOTE_SUCCESS: 'GET_RANDOM_QUOTE_SUCCESS',

	GET_PAGES: 'GET_PAGES',
	GET_WIDGETS: 'GET_WIDGETS',
	GET_PAGES_SUCCESS: 'GET_PAGES_SUCCESS',
	GET_WIDGETS_SUCCESS: 'GET_WIDGETS_SUCCESS',

	WS_CONNECT: 'WS_CONNECT',
	WS_CONNECTED: 'WS_CONNECTED',
	WS_DISCONNECT: 'WS_DISCONNECT',
	WS_DISCONNECTED: 'WS_DISCONNECTED',

	CURRENT_POMODORO_TIME_SENT: 'CURRENT_POMODORO_TIME_SENT',
	START_POMODORO_TIMER: 'START_POMODORO_TIMER',
	STOP_POMODORO_TIMER: 'STOP_POMODORO_TIMER',
	GET_CURRENT_POMODORO_TIME: 'GET_CURRENT_POMODORO_TIME',
	SET_CURRENT_POMODORO_TIME: 'SET_CURRENT_POMODORO_TIME',
	POMODORO_TIMER_STARTED: 'POMODORO_TIMER_STARTED',
	POMODORO_TIMER_STOPPED: 'POMODORO_TIMER_STOPPED',

	GET_TODAYS_WATER: 'GET_TODAYS_WATER',
	GET_TODAYS_WATER_SUCCESS: 'GET_TODAYS_WATER_SUCCESS',
	LOG_WATER: 'LOG_WATER',

	CREATE_REPEATING_RECORDS: 'CREATE_REPEATING_RECORDS',
	CREATE_REPEATING_RECORDS_SUCCESS: 'CREATE_REPEATING_RECORDS_SUCCESS',

	// local
	SELECT_PAGE: 'SELECT_PAGE',

	CREATE_WIDGET: 'CREATE_WIDGET',

	OPEN_POPOVER: 'OPEN_POPOVER',
	CLOSE_POPOVER: 'CLOSE_POPOVER',

	OPEN_WIDGET_IN_MODAL: 'OPEN_WIDGET_IN_MODAL',
	CLOSE_MODAL: 'CLOSE_MODAL',

}